messages:
  playerOnly: '&cOnly players can execute this command'
  targetRequired: '&cThis command requires a target player'
  noSelfTarget: '&cYou can''t target yourself with this command'
  targetBypass: '&cThis player can''t be targeted with this command'
  reloadSuccess: '&9Plugin reloaded successfully in &l{time}ms'
  serverDisabled: '&cYou can''t use this command on this server'
  commandHelp: '&7---- &6&l{name} {version} Command help &7----'
  commandReload: '/bungeegui reload &7- Reload the plugin'
  commandGuis: '/bungeegui guis &7 - List the loaded GUIs'
  noPermission: '&cYou don''t have permission to execute that command'
  guiListTop: '&6{count} GUIs are loaded:'
  guiListItem: '&7- &6&l{name}'

guis:
  servermenu:
    aliases: [servers, lobby]
    size: 54
    title: '&d&lExampleCraft &dserver menu'
    items:
      '0':
        type: white_stained_glass_pane
        name: ''
      '1':
        type: white_stained_glass_pane
        name: ''
      '2':
        type: white_stained_glass_pane
        name: ''
      '3':
        type: white_stained_glass_pane
        name: ''
      '4':
        type: white_stained_glass_pane
        name: ''
      '5':
        type: white_stained_glass_pane
        name: ''
      '6':
        type: white_stained_glass_pane
        name: ''
      '7':
        type: white_stained_glass_pane
        name: ''
      '8':
        type: white_stained_glass_pane
        name: ''
      '9':
        type: white_stained_glass_pane
        name: ''
      '17':
        type: white_stained_glass_pane
        name: ''
      '18':
        type: white_stained_glass_pane
        name: ''
      '26':
        type: white_stained_glass_pane
        name: ''
      '27':
        type: white_stained_glass_pane
        name: ''
      '35':
        type: white_stained_glass_pane
        name: ''
      '36':
        type: white_stained_glass_pane
        name: ''
      '44':
        type: white_stained_glass_pane
        name: ''
      '45':
        type: white_stained_glass_pane
        name: ''
      '46':
        type: white_stained_glass_pane
        name: ''
      '47':
        type: white_stained_glass_pane
        name: ''
      '48':
        type: white_stained_glass_pane
        name: ''
      '49':
        type: white_stained_glass_pane
        name: ''
      '50':
        type: white_stained_glass_pane
        name: ''
      '51':
        type: white_stained_glass_pane
        name: ''
      '52':
        type: white_stained_glass_pane
        name: ''
      '53':
        type: white_stained_glass_pane
        name: ''
      '20':
        type: player_head
        name: '&aEconomy server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTQ1ZjQ3ZmViNGQ3NWNiMzMzOTE0YmZkYjk5OWE0ODljOWQwZTMyMGQ1NDhmMzEwNDE5YWQ3MzhkMWUyNGI5In19fQ='
        commands:
        - server economy
      '22':
        type: player_head
        name: '&bCreative server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODQ0OWI5MzE4ZTMzMTU4ZTY0YTQ2YWIwZGUxMjFjM2Q0MDAwMGUzMzMyYzE1NzQ5MzJiM2M4NDlkOGZhMGRjMiJ9fX0='
        commands:
        - server creative
      '24':
        type: player_head
        name: '&cKitPvp server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjVhOTNmMTczOTI4MDYwMjZmY2ZiMmRiNzcxOGRhMjQ2Yzg4MTg5NWIzMGVjYjEyODRkODNmOTg3ZWI4In19fQ=='
        commands:
        - server kitpvp
      '30':
        type: player_head
        name: '&dPrison server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjA5M2U1ZGQwMWQ3NmQ1YzM1NTQ2MTIzMTUwMzE0ZjNlZjNkMWQ5OTMzOWQ0ZmFjNzhjZWYyODM1Y2NlZGVmYSJ9fX0='
        commands:
        - server prison
      '32':
        type: player_head
        name: '&eSkyblock server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjFiYjJjM2JkNjVjZGQ4NGE4MDRlY2E5OGI3YTQ2NzM1ZjAxZTZhMWM5MTk5ZDY2NjE2NjNkYmRiNGY1YjQifX19'
        commands:
        - server skyblock
  authors:
    aliases: [authors]
    size: 45
    title: '&6BungeeGui Authors'
    items:
      '0':
        type: nether_star
      '8':
        type: nether_star
      '36':
        type: nether_star
      '44':
        type: nether_star
      '21':
        type: player_head
        data: owner:DaniFoldi
        name: '&9&lDaniFoldi'
        lore:
        - '&1Plugin developer'
      '23':
        type: player_head
        data: owner:HgeX
        name: '&c&lHgeX'
        lore:
        - '&4Plugin developer'
    
configVersion: 3
