guis:
  servermenu:
    aliases:
    - lobby
    - servers
    size: 54
    title: '&d&lExampleCraft &dserver menu'
    items:
      'row0,row5,column0,column8':
        type: white_stained_glass_pane
      '20':
        type: player_head
        name: '&aEconomy server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTQ1ZjQ3ZmViNGQ3NWNiMzMzOTE0YmZkYjk5OWE0ODljOWQwZTMyMGQ1NDhmMzEwNDE5YWQ3MzhkMWUyNGI5In19fQ='
        commands:
        - server economy
      '22':
        type: player_head
        name: '&bCreative server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODQ0OWI5MzE4ZTMzMTU4ZTY0YTQ2YWIwZGUxMjFjM2Q0MDAwMGUzMzMyYzE1NzQ5MzJiM2M4NDlkOGZhMGRjMiJ9fX0='
        commands:
        - server creative
      '24':
        type: player_head
        name: '&cKitPvp server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjVhOTNmMTczOTI4MDYwMjZmY2ZiMmRiNzcxOGRhMjQ2Yzg4MTg5NWIzMGVjYjEyODRkODNmOTg3ZWI4In19fQ=='
        commands:
        - server kitpvp
      '30':
        type: player_head
        name: '&dPrison server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjA5M2U1ZGQwMWQ3NmQ1YzM1NTQ2MTIzMTUwMzE0ZjNlZjNkMWQ5OTMzOWQ0ZmFjNzhjZWYyODM1Y2NlZGVmYSJ9fX0='
        commands:
        - server prison
      '32':
        type: player_head
        name: '&eSkyblock server'
        data: 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjFiYjJjM2JkNjVjZGQ4NGE4MDRlY2E5OGI3YTQ2NzM1ZjAxZTZhMWM5MTk5ZDY2NjE2NjNkYmRiNGY1YjQifX19'
        commands:
        - server skyblock
  authors:
    aliases: [authors]
    size: 45
    title: '&6BungeeGui Authors'
    items:
      '0,8,36,44':
        type: nether_star
      '21':
        type: player_head
        data: owner:DaniFoldi
        name: '&9&lDaniFoldi'
        lore:
        - '&1Plugin developer'
      '23':
        type: player_head
        data: owner:HgeX
        name: '&c&lHgeX'
        lore:
        - '&4Plugin developer'
  stats:
    aliases:
    - stats
    size: 45
    title: '&4&lStatistics'
    openSound:
      sound: block_beacon_activate
      volume: 0.4
    closeable: false
    items:
      row0,row4,column0,column8:
        type: red_stained_glass_pane
        enchanted: true
        clickSound:
          sound: entity_villager_no
      '13':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzI3NDA3NjFkYmQ0MmY3NmU0ZjEyYzQ4ZWMwOTlhY2RjMWM2OTI3MmFiNTc2MzU3OWJiZTkxYzVmNTg2NTZkNyJ9fX0=
        name: '%bungeegui%'
        lore: [ 'Guis loaded: %guicount%', 'Description: %plugin_description@BungeeGUI%',
                'Version: %plugin_version@BungeeGUI%', 'Author: %plugin_author@BungeeGUI%',
                'Main class: %plugin_main@BungeeGUI%', 'Depends: %plugin_depends@BungeeGUI%',
                'Softdepends: %plugin_softdepends@BungeeGUI%' ]
      '21':
        type: player_head
        data: owner:{player}
        name: '%name%'
        lore: [ '&4Ping: %ping%', '&5Server: %servername%', '&7Vanished: %vanished%',
                'Version: %version%', 'Client locale: %locale%', 'Luckperms group: %luckperms_group%',
                'Luckperms name: %luckperms_prefix%%displayname%%luckperms_suffix%' ]
      '23':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGQxOWM2ODQ2MTY2NmFhY2Q3NjI4ZTM0YTFlMmFkMzlmZTRmMmJkZTMyZTIzMTk2M2VmM2IzNTUzMyJ9fX0=
        name: '%proxyname%'
        lore: [ 'Version: %proxyversion%', '&4Memory: %ram_used% / %ram_total% MB',
            '&5Players: %online_visible% / %max%', '&6Plugins: %plugincount%', 'Servers:
              %servercount%' ]
      '31':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjYwYjAwNGYzNjBlMjg4NTVjY2YxMjM1YzJiZGVhMGEyOTk3YjBiYzAzMjU4ZTJkYzI0YWI4YTI1NzBhZWE2In19fQ==
        name: '%servername%'
        lore: [ 'MOTD: %motd@%servername%%', 'Players: %online_visible@%servername%%
              / %max@%servername%%', 'Version: %version@%servername%%', 'Restricted:
              %restricted@%servername%% (Accessible: %canaccess@%servername%%)' ]
      '16':
        type: barrier
        clickSound:
          sound: block_beacon_deactivate
          volume: 0.4
        name: '&cClose'
        commands: [ '' ]
  sounds:
    aliases:
      - mobs
      - sounds
    title: '&5&lTest &d&lSounds'
    items:
      'row0even,row5odd,column0even,column8even':
        type: pink_stained_glass_pane
      'row0odd,row5even,column0odd,column8odd':
        type: purple_stained_glass_pane
      '10':
        type: zombie_head
        clickSound:
          sound: entity.zombie.ambient
      '12':
        type: creeper_head
        clickSound:
          sound: entity.creeper.primed
      '14':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTcxNTI4NzZiYzNhOTZkZDJhMjI5OTI0NWVkYjNiZWVmNjQ3YzhhNTZhYzg4NTNhNjg3YzNlN2I1ZDhiYiJ9fX0=
        clickSound:
          sound: entity.puffer_fish.blow_up
      '16':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmNhNDQ1NzQ5MjUxYmRkODk4ZmI4M2Y2Njc4NDRlMzhhMWRmZjc5YTE1MjlmNzlhNDI0NDdhMDU5OTMxMGVhNCJ9fX0=
        clickSound:
          sound: entity.skeleton.ambient
      '20':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzEzNWY1ODM4ZTUxNTg1ZTE1OTQyZThmMmYxY2MzNmRhOTYzMDcwZGRkNWJhMzVhZjk1ZWQzN2ViNmMzIn19fQ==
        clickSound:
          sound: entity.parrot.ambient
      '22':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQwMDk3MjcxYmI2ODBmZTk4MWU4NTllOGJhOTNmZWEyOGI4MTNiMTA0MmJkMjc3ZWEzMzI5YmVjNDkzZWVmMyJ9fX0=
        clickSound:
          sound: entity.cat.ambient
      '24':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmU4OWQ3NDQ3NWIyZmMxYTJiMjE1Y2ZjY2ZkODY1NTkyYjg1ODQzYjkyNjBlZjY3MzA0YzJkYmNjNGJiMCJ9fX0=
        clickSound:
          sound: entity.wolf.howl
          volume: 0.2
      '28':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjA3MmQ4Y2I4Mzk1YzJiYzg0NTQ3ZTZhYzliOGVkZWVkNzhjODY1OGMwZWQxYjg4M2M2MjljM2E3ZTkwIn19fQ==
        clickSound:
          sound: entity.polar_bear.warning
      '30':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODk1YWVlYzZiODQyYWRhODY2OWY4NDZkNjViYzQ5NzYyNTk3ODI0YWI5NDRmMjJmNDViZjNiYmI5NDFhYmU2YyJ9fX0=
        clickSound:
          sound: entity.slime.jump
      '32':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2YzN2Q1MjRjM2VlZDE3MWNlMTQ5ODg3ZWExZGVlNGVkMzk5OTA0NzI3ZDUyMTg2NTY4OGVjZTNiYWM3NWUifX19
        clickSound:
          sound: entity.chicken.ambient
      '34':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGJkYTFkZjgwYmZhMzE0ODUzMzhkOTYzMzgzZDhkZTI2ZjA1ZjI5MzRmODc1Njk2ODYyNDU0ZTdjNzBmNDVmNiJ9fX0=
        clickSound:
          sound: entity.cow.ambient
      '38':
        type: dragon_head
        clickSound:
          sound: entity.ender_dragon.ambient
      '40':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjVjNGQyNGFmZmRkNDgxMDI2MjAzNjE1MjdkMjE1NmUxOGMyMjNiYWU1MTg5YWM0Mzk4MTU2NDNmM2NmZjlkIn19fQ==
        clickSound:
          sound: block.shulker_box.open
      '42':
        type: player_head
        data: texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGYwMDg1ODkyNmNkOGNkZjNmMWNmNzFlMjEwY2RlNWRhZjg3MDgzMjA1NDdiZDZkZjU3OTU4NTljNjhkOWIzZiJ9fX0=
        clickSound:
          sound: entity.panda.worried_ambient
    
configVersion: 4
debugLevel: all
actions: {}