messages:
  playerOnly: '&cOnly players can execute this command'
  targetRequired: '&cThis command requires a target player'
  noSelfTarget: '&cYou can''t target yourself with this command'
  reloadSuccess: '&bPlugin reloaded successfully in &l{time}ms'
  serverDisabled: '&cYou can''t use this command on this server'

guis:
  punish:
    targeted: true # do the commands require a target player as an argument
    aliases: [punish]
    permission: 'bungeegui.gui.punish' # overrides the permission bungeegui.gui.<guiname>
    size: 54
    title: 'Punish {target}'
    items:
      1:
        type: 'WHITE_STAINED_GLASS_PANE'
        count: 10
        name: '&5próba'
        lore:
          - 'ide'
          - 'valami, de nem tomi'
        enchantments:
          unbreaking: 1
        data: 'asd'
        commands:
          - 'broadcast {target}'

configVersion: 1