messages:
  playerOnly: 'Ezt a parancsot csak player futtathattja'
  targetRequired: 'Ennek a parancsnak meg kell adnod egy céljátékost'
  reloadSuccess: 'Plugin sikeresen újratöltve {time}ms'

guis:
  punish:
    targeted: true # do the commands require a target player as an argument
    aliases: [punish]
    permission: 'bungeegui.gui.punish' # overrides the permission bungeegui.gui.<guiname>
    size: 54
    title: 'Punish {target}'
    items:
      1:
        type: 'WHITE_STAINED_GLASS_PANE'
        count: 10
        name: '&5próba'
        lore:
          - 'ide'
          - 'valami, de nem tomi'
        enchantments:
          unbreaking: 1
        data: 'asd'
        commands:
          - 'broadcast {target}'